// <auto-generated />
namespace GreenProgrammerz.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class t : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(t));
        
        string IMigrationMetadata.Id
        {
            get { return "201912071312151_t"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
